name: canteen_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  http: ^1.3.0
  logger: ^2.5.0
  mobile_scanner: ^6.0.6
  otp_autofill: ^4.1.0
  package_info_plus: ^8.2.1
  permission_handler: ^10.0.0
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/Group 8.png
      - assets/images/Group 9.png
      - assets/images/Group 10.png
      - assets/images/Home-page.png
      - assets/images/icon.png
      - assets/images/Login-Screen.png
      - assets/images/Splash-Screen.png
      
